version: 2.1 

commands:
  test-node:
    steps:
      - run:
          name: Install cricli for minikube
          command: |
              sudo apt-get update && sudo apt-get install -y cowsay

  elek:
    steps:
      - run: 
          name: Running all unit tests 
          command: |
              docker run #ricardmodi/memek:latest

  babu:
    steps:
      - run: 
          name: Running all unit tests 
          command: |
              apt update
            
jobs: 
  test: 
    parameters: 
        machine: 
          type: string 
          default: ubuntu-2004:202104-01 
    machine: 
      image: << parameters.machine >> 
 
    steps: 
      - checkout
      - test-node
      - elek
      - babu
      
workflows: 
  version: 2 
  test-all-elek: 
    jobs: 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test
 
  all-node-elek: 
    jobs: 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test
 
  all-ruby-elek: 
    jobs: 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test
 
  all-js-elek: 
    jobs: 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test
 
  all-python-elek: 
    jobs: 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test
 
  all-Net-elek: 
    jobs: 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test: 
          machine: ubuntu-2004:202104-01 
      - test